/* eslint-disable max-len */
/* eslint-disable react/require-default-props */
/* eslint-disable react/button-has-type */

'use client';

import { useState } from 'react';
import { Card, Button, Spinner } from 'react-bootstrap';

interface CompatibilityReportBoxProps {
  matchId: string;
  report?: string;
}

export default function CompatibilityReportBox({ matchId, report }: CompatibilityReportBoxProps) {
  const [aiReport, setAiReport] = useState(report || '');
  const [loading, setLoading] = useState(false);

  const generateReport = async () => {
    setLoading(true);
    try {
      const res = await fetch(`/api/matches/${matchId}/ai-report`, {
        method: 'POST',
      });
      const data = await res.json();
      setAiReport(data.report);
    } catch (err) {
      console.error('Error generating report:', err);
    } finally {
      setLoading(false);
    }
  };

  return (
    <Card className="shadow-sm h-100" style={{ border: 'none', borderRadius: '12px' }}>
      <Card.Body className="p-4">
        {/* Header */}
        <div className="d-flex align-items-center gap-3 mb-4">
          <div
            className="bg-success rounded d-flex align-items-center justify-content-center"
            style={{ width: '40px', height: '40px', flexShrink: 0 }}
          >
            <i className="bi bi-file-text text-white" style={{ fontSize: '1.25rem' }} />
          </div>
          <div>
            <h4 className="fw-bold mb-0">AI Compatibility Report</h4>
            <small className="text-muted">AI-powered analysis of your compatibility</small>
          </div>
        </div>

        {/* Content Area */}
        {!aiReport && !loading && (
          <div className="text-center py-5">
            <div
              className="bg-light rounded-circle d-flex align-items-center justify-content-center mx-auto mb-3"
              style={{ width: '60px', height: '60px' }}
            >
              <i className="bi bi-lightning text-muted" style={{ fontSize: '1.75rem' }} />
            </div>
            <p className="text-muted mb-4">
              Get a detailed AI analysis of your compatibility with this match, including strengths and potential challenges.
            </p>
            <Button
              variant="success"
              size="lg"
              onClick={generateReport}
            >
              Generate Report
            </Button>
          </div>
        )}

        {loading && (
          <div className="text-center py-5">
            <Spinner animation="border" variant="success" className="mb-3" />
            <p className="text-muted mb-0">Analyzing compatibility...</p>
            <small className="text-muted">This may take a few moments</small>
          </div>
        )}

        {aiReport && !loading && (
          <div className="bg-light rounded p-4 border border-success border-2">
            <p className="mb-0" style={{ whiteSpace: 'pre-wrap', lineHeight: '1.6' }}>
              {aiReport}
            </p>
            <hr />
            <div className="d-flex align-items-start gap-2 small text-muted">
              <i className="bi bi-info-circle" />
              <span>Generated by AI • Use this as a starting point for your decision</span>
            </div>
          </div>
        )}
      </Card.Body>
    </Card>
  );
}
